### ISSUE TITLE
Multiple Timers in foreach

### ISSUE THREAD

**Issue by Adejair** [Angular-JS2/timerc#1]
I have problems with this component in loops, he load only last timer, any idea to fix this?

```html
 <ion-card *ngFor="let oferta of dataOffers | async">

    <ion-card-header> 
      {{oferta.product}} {{oferta.productType}}
    <timerc [dt]="oferta.time"></timerc>
    <p style="float:right;font-size: 11px;">{{oferta.id}}</p>
    </ion-card-header>
      .....

</ion-card>
```

**Comment by DILEEP-YADAV** [comment]
@Adejair  Thanks for raise issue.  Component Updated Kindly checkout again and use it with 

`<timerc [dt]="product.timeend" [dtid]="product.id"></timerc>`

**Comment by Adejair** [comment]
Thanks!

**Comment by Adejair** [comment]
hey, how to get restant time of component in controller page ionic?

**Comment by DILEEP-YADAV** [comment]
Go through source code and modify as per your requirement. 

Thanks
